<?php

/**
 * This is the model base class for the table "{{form_values}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "FormValues".
 *
 * Columns in table "{{form_values}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $field_id
 * @property integer $user_id
 * @property string $value
 * @property string $created
 * @property string $updated
 *
 */
abstract class BaseFormValues extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{form_values}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'FormValues|FormValues', $n);
	}

	public static function representingColumn() {
		return array(
			'field_id',
			'user_id',
		);
	}

	public function rules() {
		return array(
			array('field_id, user_id, created', 'required'),
			array('field_id, user_id', 'numerical', 'integerOnly'=>true),
			array('value, updated', 'safe'),
			array('value, updated', 'default', 'setOnEmpty' => true, 'value' => null),
			array('field_id, user_id, value, created, updated', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'field_id' => null,
			'user_id' => null,
			'value' => Yii::t('app', 'Value'),
			'created' => Yii::t('app', 'Created'),
			'updated' => Yii::t('app', 'Updated'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('field_id', $this->field_id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('value', $this->value, true);
		$criteria->compare('created', $this->created, true);
		$criteria->compare('updated', $this->updated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}