<?php

/**
 * This is the model base class for the table "{{user_metas}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UserMetas".
 *
 * Columns in table "{{user_metas}}" available as properties of the model,
 * followed by relations of table "{{user_metas}}" available as properties of the model.
 *
 * @property integer $user_id
 * @property string $meta_name
 * @property string $meta_value
 * @property string $created
 * @property string $updated
 *
 * @property Users $user
 */
abstract class BaseUserMetas extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{user_metas}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UserMetas|UserMetases', $n);
	}

	public static function representingColumn() {
		return 'meta_value';
	}

	public function rules() {
		return array(
			array('user_id, meta_name, meta_value, created', 'required'),
			array('user_id', 'numerical', 'integerOnly'=>true),
			array('meta_name', 'length', 'max'=>255),
			array('updated', 'safe'),
			array('updated', 'default', 'setOnEmpty' => true, 'value' => null),
			array('user_id, meta_name, meta_value, created, updated', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'user' => array(self::BELONGS_TO, 'Users', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'user_id' => null,
			'meta_name' => Yii::t('app', 'Meta Name'),
			'meta_value' => Yii::t('app', 'Meta Value'),
			'created' => Yii::t('app', 'Created'),
			'updated' => Yii::t('app', 'Updated'),
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('meta_name', $this->meta_name, true);
		$criteria->compare('meta_value', $this->meta_value, true);
		$criteria->compare('created', $this->created, true);
		$criteria->compare('updated', $this->updated, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}