<?php

/**
 * This is the model base class for the table "{{org_admins}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "OrgAdmins".
 *
 * Columns in table "{{org_admins}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $org_id
 * @property integer $user_id
 * @property string $rule
 *
 */
abstract class BaseOrgAdmins extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{org_admins}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'OrgAdmins|OrgAdmins', $n);
	}

	public static function representingColumn() {
		return array(
			'org_id',
			'user_id',
		);
	}

	public function rules() {
		return array(
			array('org_id, user_id, rule', 'required'),
			array('org_id, user_id', 'numerical', 'integerOnly'=>true),
			array('rule', 'length', 'max'=>255),
			array('org_id, user_id, rule', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'org_id' => null,
			'user_id' => null,
			'rule' => Yii::t('app', 'Rule'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('org_id', $this->org_id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('rule', $this->rule, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}