<?php

/**
 * This is the model base class for the table "{{division_elms}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "DivisionElms".
 *
 * Columns in table "{{division_elms}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $div_id
 * @property integer $elm_id
 *
 */
abstract class BaseDivisionElms extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{division_elms}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'DivisionElms|DivisionElms', $n);
	}

	public static function representingColumn() {
		return array(
			'div_id',
			'elm_id',
		);
	}

	public function rules() {
		return array(
			array('div_id, elm_id', 'numerical', 'integerOnly'=>true),
			array('div_id, elm_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('div_id, elm_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'div_id' => null,
			'elm_id' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('div_id', $this->div_id);
		$criteria->compare('elm_id', $this->elm_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}