<?php

/**
 * This is the model base class for the table "{{division_choices}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "DivisionChoices".
 *
 * Columns in table "{{division_choices}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $div_id
 * @property integer $user_id
 * @property string $choosed
 * @property integer $weight
 *
 */
abstract class BaseDivisionChoices extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{division_choices}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'DivisionChoices|DivisionChoices', $n);
	}

	public static function representingColumn() {
		return array(
			'div_id',
			'user_id',
		);
	}

	public function rules() {
		return array(
			array('div_id, user_id, choosed', 'required'),
			array('div_id, user_id, weight', 'numerical', 'integerOnly'=>true),
			array('weight', 'default', 'setOnEmpty' => true, 'value' => null),
			array('div_id, user_id, choosed, weight', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'div_id' => null,
			'user_id' => null,
			'choosed' => Yii::t('app', 'Choosed'),
			'weight' => Yii::t('app', 'Weight'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('div_id', $this->div_id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('choosed', $this->choosed, true);
		$criteria->compare('weight', $this->weight);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}