<?php

/**
 * This is the model base class for the table "{{forms}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Forms".
 *
 * Columns in table "{{forms}}" available as properties of the model,
 * followed by relations of table "{{forms}}" available as properties of the model.
 *
 * @property integer $elm_id
 *
 * @property FormFields[] $formFields
 * @property OrgElms $elm
 */
abstract class BaseForms extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{forms}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Forms|Forms', $n);
	}

	public static function representingColumn() {
		return 'elm_id';
	}

	public function rules() {
		return array(
			array('elm_id', 'required'),
			array('elm_id', 'numerical', 'integerOnly'=>true),
			array('elm_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'formFields' => array(self::HAS_MANY, 'FormFields', 'form_id'),
			'elm' => array(self::BELONGS_TO, 'OrgElms', 'elm_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'elm_id' => null,
			'formFields' => null,
			'elm' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('elm_id', $this->elm_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}